// Embed the canonical skill markdown into a TS module so the `quickflo mcp`
// server can serve it as resources regardless of how the CLI is distributed
// (deno run / install / compile / JSR — where skill/ isn't published).
//
// Re-run after editing the markdown:  deno task bundle:guides
import { dirname, fromFileUrl, join } from '@std/path';

const here = dirname(fromFileUrl(import.meta.url));
const guide = await Deno.readTextFile(join(here, 'quickflo-agent-guide.md'));
const building = await Deno.readTextFile(join(here, 'building-workflows.md'));

const out = `// GENERATED by skill/bundle-guides.ts — do not edit by hand.
// Re-run \`deno task bundle:guides\` after changing skill/*.md.
export const AGENT_GUIDE = ${JSON.stringify(guide)};
export const BUILDING_WORKFLOWS = ${JSON.stringify(building)};
`;

await Deno.writeTextFile(join(here, '..', 'src', 'skill-guides.ts'), out);
console.error(
  `wrote src/skill-guides.ts (agent-guide ${guide.length}B, building-workflows ${building.length}B)`,
);
